name: Build

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@v1.0.1
      with:
        nim-version: '1.0.4'
    - run: nimble build -Y
